### ISSUE TITLE
SyntaxError in Python 3

### ISSUE THREAD

**Issue by drzero42** [uber/jaeger-client-python#41] opened 2017-04-26 12:57 UTC
The function codecs.span_context_to_string has the following line in it:

`parent_id = parent_id or 0L`

This is invalid syntax in Python 3 as per [PEP 237](https://www.python.org/dev/peps/pep-0237/), as can be seen here:
`SyntaxError: invalid syntax
 Traceback (most recent call last):
   File "/usr/local/lib/python3.6/site-packages/jaeger_client/__init__.py", line 32, in <module>
     from .tracer import Tracer  # noqa
   File "/usr/local/lib/python3.6/site-packages/jaeger_client/tracer.py", line 34, in <module>
     from .codecs import TextCodec, ZipkinCodec, ZipkinSpanFormat, BinaryCodec
   File "/usr/local/lib/python3.6/site-packages/jaeger_client/codecs.py", line 140
     parent_id = parent_id or 0L
                               ^
 SyntaxError: invalid syntax`

Instead of 0L in should just be 0. Not sure how to make in compatible with both 2 and 3 though.

**Comment by drzero42** [comment] 2017-04-26 13:19
Okay, it seems there are various Python 3 incompatibilities in here. My guess is that this is because of Thrift? From what I can see Thrift is Python 3 compatible from version 0.10.0.
What would be needed to get jaeger_client to be Python 3 compatible?

**Comment by yurishkuro** [comment] 2017-04-26 16:16
the setup.py does not pin thrift to 0.9, and if I look at the latest build from master, I can see that it is in fact thrift 0.10 that is installed. The crossdock test includes an end-to-end test where the client communicates with jaeger-agent, so I think it is safe to assume using thrift-0.10 is fine and compatible with Jaeger backend (even if jaeger-agent is using 0.9)

**Comment by xdralex** [comment] 2017-05-02 21:50
@drzero42 @yurishkuro I think I have fixed most of the incompatibilities in #43 - feel free to take a look.

**Comment by I159** [comment] 2017-08-11 11:16
`$ python --version`
`Python 3.6.1`

`pip freeze | grep jaeger`
`jaeger-client==2.1.0`

`$ pip freeze | grep thrift`
 `thrift==0.10.0`

And I still experiencing the error:
`
python3.6/site-packages/jaeger_client/codecs.py", line 88
parent_id = parent_id or 0L
`

**Comment by yurishkuro** [comment] 2017-08-11 20:31
this was fixed in #57, but we haven't released a new version since the work is not finished.

There doesn't seem to be any new information in this ticket, so I am going to close it as a dupe of #59.

**Closed by yurishkuro** 2017-08-11 20:31 UTC
Labels: help wanted
